name: API Doc Preview Status

on:
  workflow_dispatch:
    inputs:
      SHA:
        type: string
        required: true
        description: SHA to assign check to (generally the latest commit in the head branch)
      Description:
        type: string
        required: true
        description: A string displayed next to the status name/context that describes current status
      TargetUrl:
        type: string
        required: true
        description: URL to link to when the status name is clicked
      Conclusion:
        type: choice
        options: ["error", "failure", "pending", "success"]

permissions:
  statuses: write

jobs:
  ubuntu: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          SHA: ${{ inputs.SHA }}
          DESCRIPTION: ${{ inputs.Description }}
          TARGET_URL: ${{ inputs.TargetUrl }}
          CONCLUSION: ${{ inputs.Conclusion }}
        with:
          script: |
            const commitStatus = await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: process.env.SHA,
              state: process.env.CONCLUSION,
              context: 'Swagger ApiDocPreview',
              description: process.env.DESCRIPTION,
              target_url: process.env.TARGET_URL,
            });
            console.log(commitStatus);
