name: test2

on:
  workflow_dispatch:
    inputs:
      SHA:
        type: string
        required: true
      Markdown:
        type: string
        required: true
      Conclusion:
        type: choice
        options: ["success", "failure", "neutral", "cancelled", "timed_out", "action_required", "skipped"]

permissions:
  checks: write

jobs:
  ubuntu: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          SHA: ${{ inputs.SHA }}
          MARKDOWN: ${{ inputs.Markdown }}
          CONCLUSION: ${{ inputs.Conclusion }}
        with:
          script: |
            const suite = await github.rest.checks.createSuite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: process.env.SHA,
            });
            console.log(suite);
            console.log('-----------------------------------');
            const result = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Docs preview 2",
              head_sha: process.env.SHA,
              details_url: 'https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5058060&view=logs&j=407c8e09-36f7-5b0b-5ef1-9a46f011447b&t=b7bb9f89-2346-5516-09dd-ff209e5433c8&l=63',
              external_id: '123',
              status: 'completed',
              conclusion: process.env.CONCLUSION,
              output: { 
                title: 'Click here to see a preview', 
                summary: '[Preview](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5058060&view=logs&j=407c8e09-36f7-5b0b-5ef1-9a46f011447b&t=b7bb9f89-2346-5516-09dd-ff209e5433c8&l=63)' 
              },
            });
            
            console.log(result);
