name: test

on:
  workflow_dispatch:
    inputs:
      sha:
        required: true
        type: string
      markdown:
        required: true
        type: string

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world'

