name: test

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: internal
    steps:
      - name: Say hello
        run: |
          echo "Hello world"
          echo "Hello ${{ secrets.TEST_SECRET }}"
