name: test

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo 'hello={"hello": "world"}' >> $GITHUB_OUTPUT
        id: hello-world

      - run: echo "${{ steps.hello-world.outputs.hello}}"

      - run: echo "IT WORKED!!" 
        if: steps.hello-world.outputs.hello == 'world'
