name: wsl

on:
  pull_request: 
    branches: [main]
  push: 
    branches: [main]

jobs:
  run-wsl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(`Current SHA: ${context.sha}`);
