name: wsl

on:
  pull_request: 
    branches: [main]
  push: 
    branches: [main]

jobs:
  run-wsl:
    runs-on: windows-2022
    steps:
      - name: Run WSL 
        shell: pwsh
        run: |
          Write-Host "wsl --status" 
          wsl --status 

          Write-Host "wsl --list --online" 
          wsl --list --online

          write-host "WSL install of ubuntu."
          Write-Host "wsl --install -d Ubuntu-20.04"
          wsl --install -d Ubuntu-20.04

          Write-Host "wsl --list --all --verbose | out-string"
          $wsl = wsl --list --all --verbose | out-string
          write-host $wsl

          while ($wsl -notmatch 'Ubuntu-20.04.*[Rr]unning') {
            start-sleep -seconds 1
            Write-Host "wsl --list --all --verbose | out-string"
            $wsl = wsl --list --all --verbose | out-string
            write-host $wsl

            Write-Host "wsl --status"
            wsl --status
          }
          write-host "Ubuntu installed."
